const rows=document.querySelector('#lead-rows'),form=document.querySelector('#lead-form'),result=document.querySelector('#result'),fields=document.querySelector('#fields');
const schema=[['company','Company','text'],['contact_name','Contact','text'],['industry','Industry','text'],['employee_count','Employees','number'],['email_opens','Email opens','number'],['days_since_activity','Days since activity','number'],['pain_point','Pain point','textarea'],['source','Source','text']];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
let leads=[],analyses=[],selected=null,filter='All',audit=[];
for(const [name,label,type] of schema){const wrap=document.createElement('label');wrap.textContent=label;const control=type==='textarea'?document.createElement('textarea'):document.createElement('input');control.name=name;control.type=type==='textarea'?undefined:type;wrap.append(control);fields.append(wrap)}
const checks=document.createElement('div');checks.className='checks';for(const [name,label] of [['visited_pricing','Visited pricing'],['requested_demo','Requested demo']]){const l=document.createElement('label'),i=document.createElement('input');i.type='checkbox';i.name=name;l.append(i,' '+label);checks.append(l)}fields.append(checks);
async function analyze(lead){const r=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(lead)});const data=await r.json();if(!r.ok)throw new Error(data.error||'Analysis failed');return data}
async function load(){try{leads=await fetch('/demo/leads.json').then(r=>r.json());analyses=await Promise.all(leads.map(analyze));sortData();renderMetrics();renderRows();selectLead(0)}catch(error){rows.innerHTML=`<tr><td colspan="6">${esc(error.message)}. Start this project with <code>python app.py</code>.</td></tr>`}}
function sortData(){const paired=leads.map((lead,i)=>({lead,analysis:analyses[i]})).sort((a,b)=>b.analysis.score-a.analysis.score);leads=paired.map(x=>x.lead);analyses=paired.map(x=>x.analysis)}
function renderMetrics(){document.querySelector('#lead-count').textContent=leads.length;document.querySelector('#high-count').textContent=analyses.filter(x=>x.tier==='High').length;document.querySelector('#demo-count').textContent=leads.filter(x=>x.requested_demo).length;document.querySelector('#average-score').textContent=Math.round(analyses.reduce((n,x)=>n+x.score,0)/analyses.length)}
function renderRows(){rows.innerHTML=analyses.map((a,i)=>filter==='All'||a.tier===filter?`<tr data-index="${i}" class="${selected===i?'selected':''}"><td><b class="table-score">${a.score}</b><span class="tier ${a.tier.toLowerCase()}">${esc(a.tier)}</span></td><td><strong>${esc(a.company)}</strong><small>${esc(leads[i].lead_id)}</small></td><td>${esc(a.contact_name)}</td><td>${esc(a.industry)}</td><td>${a.requested_demo?'Demo requested':a.visited_pricing?'Pricing visit':a.email_opens+' email opens'}</td><td>${esc(a.recommended_timing)}</td></tr>`:'').join('')||'<tr><td colspan="6">No leads match this filter.</td></tr>';rows.querySelectorAll('tr[data-index]').forEach(row=>row.onclick=()=>selectLead(Number(row.dataset.index)))}
function selectLead(index){selected=index;const lead=leads[index];document.querySelector('#detail-title').textContent=lead.company;for(const [key,value] of Object.entries(lead)){const field=form.elements[key];if(field)field.type==='checkbox'?field.checked=Boolean(value):field.value=value}renderResult(analyses[index]);renderRows();document.querySelector('#workspace').scrollIntoView({behavior:'smooth',block:'start'})}
function renderResult(out){const reasons=out.reasons.map(reason=>{const points=Number((reason.match(/^\+(\d+)/)||[])[1]||0);return `<div class="signal"><div><span>${esc(reason.replace(/^\+\d+: /,''))}</span><b>+${points}</b></div><i style="width:${Math.min(100,points*4)}%"></i></div>`}).join('')||'<p>No positive intent signals detected.</p>';result.innerHTML=`<div class="score-row"><div><p class="eyebrow">OPPORTUNITY SCORE</p><div class="score">${out.score}</div></div><div><span class="tier ${out.tier.toLowerCase()}">${esc(out.tier)} priority</span><p>${esc(out.mode)} mode</p></div></div><section><h3>Why this account now?</h3>${reasons}</section><section><h3>Account brief</h3><p>${esc(out.brief)}</p></section><section class="action-card"><p class="eyebrow">NEXT BEST ACTION</p><strong>${esc(out.next_action)}</strong><small>${esc(out.recommended_timing)}</small></section><section class="outreach"><div class="section-head"><div><h3>Editable outreach draft</h3><p>Review and personalize before use.</p></div><button id="copy-draft" class="secondary">Copy</button></div><textarea id="draft" rows="10">${esc(out.outreach_draft)}</textarea><button id="approve-draft">Approve for CRM handoff (demo)</button><p class="guardrail">Nothing is sent. Approval creates only a session audit event.</p></section>`;document.querySelector('#copy-draft').onclick=async e=>{await navigator.clipboard.writeText(document.querySelector('#draft').value);e.currentTarget.textContent='Copied ✓'};document.querySelector('#approve-draft').onclick=()=>record(out.company,'Outreach approved for mock CRM handoff')}
form.onsubmit=async event=>{event.preventDefault();const error=document.querySelector('#form-error'),button=document.querySelector('#reanalyze');error.textContent='';const data=Object.fromEntries(new FormData(form));const required=schema.map(x=>x[0]),missing=required.filter(k=>!String(data[k]??'').trim());if(missing.length){error.textContent='Complete: '+missing.map(x=>x.replaceAll('_',' ')).join(', ')+'.';return}for(const key of ['employee_count','email_opens','days_since_activity'])data[key]=Number(data[key]);for(const key of ['visited_pricing','requested_demo'])data[key]=form.elements[key].checked;data.is_demo_data=true;data.lead_id=leads[selected].lead_id;button.disabled=true;button.textContent='Recalculating…';try{const out=await analyze(data);leads[selected]=data;analyses[selected]=out;renderMetrics();renderRows();renderResult(out);record(out.company,'CRM signals edited and score recalculated')}catch(e){error.textContent=e.message}finally{button.disabled=false;button.textContent='Save edits & rerun score →'}};
function record(account,action){audit.unshift({account,action,time:new Date().toLocaleTimeString()});document.querySelector('#audit-list').innerHTML=audit.map(x=>`<div class="audit-event"><b>${esc(x.account)}</b><span>${esc(x.action)}</span><time>${esc(x.time)}</time></div>`).join('')}
document.querySelectorAll('.filter').forEach(button=>button.onclick=()=>{filter=button.dataset.filter;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===button));renderRows()});document.querySelector('#crm-sync').onclick=e=>{e.currentTarget.textContent='CRM demo synced ✓';record('Demo CRM','Synthetic lead queue refreshed')};
load();
